### ISSUE TITLE
Provide example on increasing font size of list.

### ISSUE THREAD

**Issue by mikezimm** [mikezimm/drilldown7#169]

**Comment by mikezimm** [comment]
## The way to make it totally flexible would be too complex to code and also for typical end user to adjust.

Also given that everyone can have screens of any size from phones to 32" monitors, setting a specific value might make it harder for some users to read.

## Solution - add a button to easily cycle through 3 sizes:  inherit, larger, large (which match the css font-size options

inherit:  Smallest and default
![image](https://user-images.githubusercontent.com/49648086/190543517-3d12fb09-849e-4659-89c0-6db0238ed311.png)

larger:  larger than inherit
![image](https://user-images.githubusercontent.com/49648086/190543558-6c63a794-46e6-495c-9f81-f2e45f746658.png)

large:  largest
![image](https://user-images.githubusercontent.com/49648086/190543590-102e1d45-8fec-4d4a-8f68-27c7798b598b.png)

**Comment by herculesjia** [comment]
Hello Mike,
Really appreciate for your hard work for the feature development of the web part.
1.for the resizable font feature:
I think the resize font dynamically should be okay.
But is that possible to configure the 3 sizes by CSS or configuration within the web part configuration as well for the SharePoint admin?

2.popup or suspending window for the long description words:
Another expectation is, for the long description of the word, is that possible to show a suspending window once the mouse move over these kind of cell?

Thank you so much for your great support!

Br,

Hercules Jia
