### ISSUE TITLE
BUG - You need to put a space in the rest filter property to not get json error

### ISSUE THREAD

**Issue by McDKirra** [mikezimm/drilldown7#21]
see title

**Comment by mikezimm** [comment]
## I have no clue what the error is about... but I do have some screenshots in history from that day:

![image](https://user-images.githubusercontent.com/49648086/193867003-82916fe3-cda5-41b6-a7d5-a842aeacd3d3.png)

**Comment by mikezimm** [comment]
Closing because there is to little info to go on at the moment
