### ISSUE TITLE
Have Refiner option to show new filetype in fps-library-v2 v1.0.140+

### ISSUE THREAD

**Issue by mikezimm** [mikezimm/drilldown7#329]
Include an option for filetype and also groupContent

**Comment by Bullssf** [comment]
delete

**Comment by mikezimm** [comment]
@Bullssf
What were you meaning?

**Comment by mikezimm** [comment]
## Looks like this is now resolved.... Not sure when but it does show a file icon to match the file type

![image](https://github.com/mikezimm/drilldown7/assets/49648086/3088658a-a27d-42b2-bc68-326fc9b1f841)
