### ISSUE TITLE
Clicking ID while item selected takes me to item same tab and not in new window

### ISSUE THREAD

**Issue by McDKirra** [mikezimm/drilldown7#330]
I want the form to open in new window not same tab when I click on the item while its selected / checkmark

<img width="241" alt="2023-03-31 18_07_37-" src="https://user-images.githubusercontent.com/35781691/229158820-e5e5753f-eee3-468c-98df-d90e1d37dbe3.png">
<img width="239" alt="2023-03-31 18_08_04-" src="https://user-images.githubusercontent.com/35781691/229158828-7ddd66d2-2fcb-4422-9240-2531c09c62d2.png">

**Comment by mikezimm** [comment]
## Confirmed this now goes to a new page
Tested:  NaSupAamIndirectPurch/SitePages/Sourcing-Council-Meetings---Mike-Sandbox.aspx

  {
    "name": "ID",
    "displayName": "ID",
    "minWidth": 30,
    "maxWidth": 50,
    "linkPropertyName": "goToPropsLink"
  },
